### ISSUE TITLE
Calling "library.get.albums" only returns one object

### ISSUE THREAD

**Issue by My-Random-Thoughts** [hklages/node-red-contrib-sonos-plus#161] opened 2021-07-29 16:46 UTC
### Description
I know for a fact that I have 4 albums called "The Definitive Collection" in my music library.  Browsing to `http://{player}:1400/status/tracks` lists everything my Sonos knows about and searching that list returns all the tracks in each of the 4 albums.

However using a simple inject node with a payload of "The Definitive Collection" and topic of "library.get.albums", sending that to MySonos node it only returns one result 

EDIT: It's always the same one every time I run it too

Thanks

### What node/command (topic)/state (payload)
node: My Sonos
command: library.get.albums
state: ?

### In case of a bug: Are you able to reproduce the error
Yes

### Versions and Infrastructure
**what system:** Docker
**node-red-contrib-sonos-plus version:** 5.1.1
**Node-RED version:** 2.0.4
**NodeJS version:** 14.17.3

see: [https://flows.nodered.org/flow/a5c42641bf33dd0da9bfd4426a06950a]

**Comment by hklages** [comment] 2021-07-29 18:44
Is that specific to this album or also for others: eg if you specify "Girl" or "Love" what should appear in a lot of album titles

**Comment by My-Random-Thoughts** [comment] 2021-07-29 19:22
Searching for:
"Love" is correct, gives 52 results, I have 52 albums. (mostly the wifes, honest)
"Hello" is correct
"Girl" is wrong, gives 6 results, I have 9 albums
"Live" is wrong, gives 27, I have 31

It's very strange and intermittent.

**Comment by hklages** [comment] 2021-07-30 06:52
Thanks for checking that.
Do the missing albums include special characters such as #'&...

**Comment by My-Random-Thoughts** [comment] 2021-07-30 08:36
So doing some detailed checks of comparing the output with the actual albums I have, the above "Girl" and "Love" are actually correct.  I was just counting raw folders in my searching before.   My music is meticulous organised.

Searching "Definitive" is still definitely wrong:

![image](https://user-images.githubusercontent.com/21334396/127625925-e3347597-4bd9-45a9-94ba-6bf8a8e56aa8.png)
![image](https://user-images.githubusercontent.com/21334396/127625582-45619e2c-9447-4cc0-af0e-e1173bf851d2.png)

I'll try to find some more instances.

**Comment by My-Random-Thoughts** [comment] 2021-07-30 19:17
A bit more info.  I use the [unoffical-sonos-controller-for-linux](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux) for my music selection and that too only returns one item for "The Definitive Collection".

I think the reason the the others results above being correct is that their titles are all different.  "The Definitive Collection" albums, while by different artists are all the same title.

Strangely, going to http://{sonos}:1400/status/tracks, does actually list all four albums.

**Comment by hklages** [comment] 2021-07-31 13:45
Thanks. That helps me a lot. I will work on it next week.

One thing: Did you recently do a rescan of the library?

**Comment by My-Random-Thoughts** [comment] 2021-07-31 15:04
My library has not changed for a while, but it does get automatically scanned once a week

**Comment by hklages** [comment] 2021-08-03 21:04
Do you have installed the Android or IPhone app? 

What do you get when you use the "find" tab and select as category "Album" and text "The Definitive Collection"?

**Comment by My-Random-Thoughts** [comment] 2021-08-03 21:15
I don't have the app, so I can't test that, sorry.
I have tried installing it, but it does not like my network and I don't like their privacy policy

**Comment by hklages** [comment] 2021-08-03 21:16
what about the windows version? 

What happen if you use library.get.album without any payload? 
How many album do you have in you library?

**Comment by My-Random-Thoughts** [comment] 2021-08-03 21:43
I have this code to get all my albums, 2301-ish
It loops through A-Z using that single letter as the payload, saving all the data to a JSON file.
The flow then reads this file and removes all the duplicates

```
[{"id":"c2d7416e736734ba","type":"inject","z":"fa21f67cc8782fbe","name":"START","props":[],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":290,"y":40,"wires":[["6305dd22e238f632"]]},{"id":"6305dd22e238f632","type":"change","z":"fa21f67cc8782fbe","name":"SET DATA PATH","rules":[{"t":"set","p":"dataPath","pt":"flow","to":"/data","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":470,"y":40,"wires":[["ecb794aa9393720c"]]},{"id":"ecb794aa9393720c","type":"link out","z":"fa21f67cc8782fbe","name":"Start","links":["0c86a398524f9c78"],"x":615,"y":40,"wires":[]},{"id":"26299b2c0e5b86f0","type":"group","z":"fa21f67cc8782fbe","name":"Complie Album / Arists Data From Sonos","style":{"stroke":"#777777","fill":"#d1d1d1","fill-opacity":"0.25","label":true,"color":"#000000"},"nodes":["05e1d93f277db6cb","d2282bb87ad57f8f","b8dbc9136952c9ec","9673d48542d59b24","7f8c35111baa40c1","34a8d90e0e8c3360","1c63b089b7ea9ca1","45129a7cf15949ab","804c3bf3ca515b34","4c9ef48f66064c5c","74d7c3d102b5296d","ac6e3f8c2a6b3764","43285661b29bc646","b2e82774021bda09","3db49bbf5b18c42a","239e8b18c7dc0831","0c86a398524f9c78","f6b4ec09781f23e1"],"x":14,"y":79,"w":1112,"h":302},{"id":"05e1d93f277db6cb","type":"trigger","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Trigger","op1":"","op2":"","op1type":"nul","op2type":"payl","duration":"5","extend":true,"overrideDelay":false,"units":"s","reset":"","bytopic":"all","topic":"topic","outputs":1,"x":440,"y":260,"wires":[["d2282bb87ad57f8f"]]},{"id":"d2282bb87ad57f8f","type":"file in","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Load RAW","filename":"","format":"utf8","chunk":false,"sendError":false,"encoding":"utf8","allProps":false,"x":610,"y":260,"wires":[["b8dbc9136952c9ec"]]},{"id":"b8dbc9136952c9ec","type":"change","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Fix JSON","rules":[{"t":"change","p":"payload","pt":"msg","from":"[]","fromt":"str","to":"","tot":"str"},{"t":"change","p":"payload","pt":"msg","from":"][","fromt":"str","to":",","tot":"str"},{"t":"change","p":"payload","pt":"msg","from":",,","fromt":"str","to":",","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":780,"y":260,"wires":[["7f8c35111baa40c1"]]},{"id":"9673d48542d59b24","type":"file","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Save Albums","filename":"","appendNewline":false,"createDir":false,"overwriteFile":"true","encoding":"utf8","x":1030,"y":300,"wires":[[]]},{"id":"7f8c35111baa40c1","type":"json","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Convert","property":"payload","action":"","pretty":false,"x":680,"y":320,"wires":[["34a8d90e0e8c3360"]]},{"id":"34a8d90e0e8c3360","type":"function","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Unique","func":"function getUniqueList(array, key, returnAll) {\n    if (returnAll === true) {\n        // Return ALL objects \n        return [...new Map(array.map(item => [item[key], item])).values()];\n    }\n    else {\n        // Return just the item\n        return [...new Map(array.map(item => [item[key], item[key]])).values()];\n    }\n}\n\nvar albums = {};\nvar artists = {};\nvar dataPath = flow.get(\"dataPath\") || \"/data\";\ndataPath = `${dataPath}/music-`;\n\nalbums.payload = getUniqueList(msg.payload, \"id\", true);\nartists.payload = getUniqueList(albums.payload, \"artist\", false);\n\nalbums.filename = `${dataPath}albums.json`;\nartists.filename = `${dataPath}artists.json`;\n\nnode.status({\n    fill:\"green\",\n    shape:\"dot\",\n    text:`Albums: ${albums.payload.length}, Artists: ${artists.payload.length}`\n});\n\nreturn [\n    {\"filename\": `${dataPath}raw.json`},\n    albums,\n    artists,\n];\n","outputs":3,"noerr":0,"initialize":"","finalize":"","libs":[],"x":840,"y":320,"wires":[["1c63b089b7ea9ca1"],["9673d48542d59b24"],["45129a7cf15949ab"]]},{"id":"1c63b089b7ea9ca1","type":"file","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Delete RAW","filename":"","appendNewline":true,"createDir":false,"overwriteFile":"delete","encoding":"none","x":1030,"y":260,"wires":[[]]},{"id":"45129a7cf15949ab","type":"file","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Save Artists","filename":"","appendNewline":false,"createDir":false,"overwriteFile":"true","encoding":"utf8","x":1030,"y":340,"wires":[[]]},{"id":"804c3bf3ca515b34","type":"sonos-manage-mysonos","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","confignode":"2fb67e61a2b0d13e","command":"library.get.albums","state":"","stateType":"str","avoidCheckPlayerAvailability":false,"name":"Get Albums","x":610,"y":200,"wires":[["ac6e3f8c2a6b3764"]]},{"id":"4c9ef48f66064c5c","type":"function","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Get Albums","func":"var index = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\nvar dataPath = flow.get(\"dataPath\") || \"/data\";\ndataPath = `${dataPath}/music-`;\n\nindex.split(\"\").forEach(item => {\n    msg.topic = \"library.get.albums\";\n    msg.payload = `${item}`;\n    msg.searchFor = `${item}`;\n    msg.filename = `${dataPath}raw.json`;\n    node.send(msg);\n});\n\nnode.done();\n","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":210,"y":200,"wires":[["43285661b29bc646"]]},{"id":"74d7c3d102b5296d","type":"inject","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Update SONOS Albums","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"00 04 * * 1","once":false,"onceDelay":0.1,"topic":"SONOS","payloadType":"date","x":170,"y":120,"wires":[["4c9ef48f66064c5c","f6b4ec09781f23e1"]]},{"id":"ac6e3f8c2a6b3764","type":"function","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Parse Data","func":"var albums = [];\nvar dataPath = flow.get(\"dataPath\") || \"/data\";\ndataPath = `${dataPath}/music-`;\n\nnode.status({\n    fill:  \"blue\",\n    shape: \"ring\",\n    text:  `${msg.searchFor} : ${msg.payload.length}`\n});\n\nmsg.payload.forEach(item => {\n    albums.push({\n        \"id\":     item.id,\n        \"title\":  item.title,\n        \"artist\": item.artist,\n        \"uri\":    item.uri,\n        \"artUri\": item.artUri\n    })\n})\n\nmsg.payload = albums;\nmsg.filename = `${dataPath}raw.json`\nnode.status({});\n\nreturn msg;\n","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":790,"y":200,"wires":[["b2e82774021bda09"]]},{"id":"43285661b29bc646","type":"delay","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"","pauseType":"rate","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"allowrate":false,"x":410,"y":200,"wires":[["804c3bf3ca515b34","05e1d93f277db6cb"]]},{"id":"b2e82774021bda09","type":"file","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Save RAW","filename":"","appendNewline":false,"createDir":false,"overwriteFile":"false","encoding":"utf8","x":1030,"y":200,"wires":[[]]},{"id":"3db49bbf5b18c42a","type":"inject","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"RESET","props":[{"p":"reset","v":"true","vt":"bool"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":230,"y":240,"wires":[["43285661b29bc646"]]},{"id":"239e8b18c7dc0831","type":"comment","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"What This Does","info":"## TOP ROW\nNOTE: This should only need to run once a week or so depending on how often you update your Sonos library.\n\nFirst this runs though the `0-9`/`A-Z` list and passes that as a search to the \"`library.get.albums`\" topic of the MySonos node.\nThe node will then return all albums that contain the specified character - maxing out at 1000.\nThis of course will create a lot of duplicate entries.\n\nSpecific details are then saved to a file called \"`/data/music-raw.json`\"\n\n---\n\n## TRIGGER\nOnce the list as been completed, the trigger will fire after 5 seconds and kick off the second part of the group.\n\n---\n\n## BOTTOM ROW\nFirst the raw file from earlier is loaded as plain text.\nIt then fixes the JSON issues that are present and converts it in to an object.\n\nNext, using a simple function we remove all duplicate enries using the album art URL as the unique key.\n\nThe list of artists and albums are then separated and saved into \"`/data/music-artists.json`\" and \"`/data/music-albums.json`\"\n","x":460,"y":340,"wires":[]},{"id":"0c86a398524f9c78","type":"link in","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Start","links":["ecb794aa9393720c","fb6582893d65689e"],"x":55,"y":200,"wires":[["4c9ef48f66064c5c"]]},{"id":"f6b4ec09781f23e1","type":"function","z":"fa21f67cc8782fbe","g":"26299b2c0e5b86f0","name":"Last Updated On","func":"msg.payload = (new Date(msg.payload).toLocaleTimeString(\"en-GB\", { timeStyle: \"short\", hour12: false }));\n\n// Node Status Text\nnode.status({\n    fill: \"green\",\n    shape: \"dot\",\n    text: `Updated: ${msg.payload}`\n});\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":430,"y":120,"wires":[[]]},{"id":"2fb67e61a2b0d13e","type":"sonos-config","name":"Kitchen","serialnum":"","ipaddress":"192.168.42.231"}]
```

**Comment by hklages** [comment] 2021-08-04 18:52
In a first step, I will change library.get.album and make it possible to retrieve up to 9999 albums, currently 1000 are possible. 
Hopefully then all your "Definitive" will show up. Then I can change that to the play commands. 
5.2.2 should be available tomorrow - have to do some testing.  

Interesting flow above (to retrieve all albums, artist) - good idea to do it for each character/digit.

**Comment by hklages** [comment] 2021-08-05 14:31
5.2.2 is now available. 
please use msg.requestedCount = 2500 with library.get.albums for you music library

Do you receive all your albums, when not specifying any search string?
Do you receive al your "Definite" albums when using that as string?

**Comment by My-Random-Thoughts** [comment] 2021-08-05 14:50
Nope, I am still only getting 1000, I think it might be a limitation of my Sonos speakers

Running the below, the "Parse" node shows the number of items found, it maxes at 1000.
If it's working on yours, then it must be a firmware issue, as mine is quite old.


```
[{"id":"a3281de7beaf8a04","type":"sonos-manage-mysonos","z":"62a67e93524bc53b","confignode":"2fb67e61a2b0d13e","command":"message","state":"","stateType":"str","avoidCheckPlayerAvailability":false,"name":"Get Albums","x":370,"y":180,"wires":[["a2f0e849a6858d96"]]},{"id":"19c16319990283e1","type":"inject","z":"62a67e93524bc53b","name":"Definitive","props":[{"p":"payload"},{"p":"topic","vt":"str"},{"p":"requestedCount","v":"2500","vt":"num"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"library.get.albums","payload":"The Definitive Collection","payloadType":"str","x":180,"y":140,"wires":[["a3281de7beaf8a04"]]},{"id":"178948fe181220e8","type":"debug","z":"62a67e93524bc53b","name":"Output","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":670,"y":180,"wires":[]},{"id":"a2f0e849a6858d96","type":"function","z":"62a67e93524bc53b","name":"Parse","func":"msg.payload.forEach(item => {\n    node.send({\n        payload: item.title\n    })\n})\n\nnode.status({fill:\"green\",shape:\"ring\",text:msg.payload.length});\n\nnode.done();","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":530,"y":180,"wires":[["178948fe181220e8"]]},{"id":"b7ffc037c6dc8098","type":"inject","z":"62a67e93524bc53b","name":"Get All","props":[{"p":"requestedCount","v":"2500","vt":"num"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"library.get.albums","x":190,"y":180,"wires":[["a3281de7beaf8a04"]]},{"id":"927ac629fa6aadfa","type":"inject","z":"62a67e93524bc53b","name":"Get Q","props":[{"p":"requestedCount","v":"2500","vt":"num"},{"p":"topic","vt":"str"},{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"library.get.albums","payload":"Q","payloadType":"str","x":190,"y":220,"wires":[["a3281de7beaf8a04"]]},{"id":"2fb67e61a2b0d13e","type":"sonos-config","name":"Kitchen","serialnum":"","ipaddress":"192.168.42.231"}]
```

**Comment by hklages** [comment] 2021-08-05 15:32
You are right. The SONOS limitation is 1000 in one call. 
I could not test it because I only have 400 albums. 

There are 2700 track in my library. I will implemented get.library.tracks and test it. There is a "starting position". That could be a solution: Doing several requests and merging them. 

Tomorrow.

**Comment by hklages** [comment] 2021-08-05 15:32
You are right. The SONOS limitation is 1000. 
I could not test it because I only have 400 albums. 

But I now implemented get.library.tracks and with that I can test it.

**Comment by My-Random-Thoughts** [comment] 2021-08-05 16:10
No rush, thank you.
Only 400, you need to boost those numbers  :D

**Comment by hklages** [comment] 2021-08-06 13:09
5.2.4 is available. 
You should now be able to retrieve up to 10,000 items (playlists, artists, albums, tracks) - even without msg.requestedCount.

Do you receive all your albums, when not specifying any search string?
Do you receive al your "Definite" albums when using that as string?

**Comment by My-Random-Thoughts** [comment] 2021-08-06 13:28
Thank you.

Calling `library.get.albums` with no requestedCount value returns the same number as my code above (2301), and quicker.   :)
Specifying "The Definitive Collection" still only returns one item  :(

I might have to just use `http://{sonos}:1400/status/tracks` and parse the data that way.  It doesn't give me all the info though (album art, etc).

**Comment by hklages** [comment] 2021-08-06 14:10
Good to hear. So one step forward :-) 

Yes it should be much quicker as it uses only 3 calls (0..999, 1000..1999, 2000 .. 2301) 
Do you know JSONata? You can use the library.get.albums and add a change node after to filter the "The Definitive Collection"

Here is an example: 
`[{"id":"365138b2caf66315","type":"change","z":"fcb24b59.997048","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"$.payload[$contains(title, /Girl/i)]","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":1520,"y":2140,"wires":[["c79ba1450bf98be3"]]}]`

Does that work for you?

**Comment by My-Random-Thoughts** [comment] 2021-08-06 15:16
Thanks, I have used JSONata a little, but know RegEx quite well.  That still only returns one result for "The Definitive Collection".

So I have just spent the last hour manually sorting through all the albums I have on my NAS and comparing that against your node (and therefore the Sonos).  I have 2387 albums, the Sonos is returning 2301.
All the missing entries have duplicate names to existing entries.

I am going to see if I can get the Sonos app remove my entire library and re-add it.  See if that works.

**Comment by My-Random-Thoughts** [comment] 2021-08-17 20:16
OK, I have updated all my Sonos speakers to the latest version for them and removed then re-added my music library and performed a complete rescan.  It's still only showing one entry for "The Definitive Collection".

I am thinking it might be a Sonos issue and not your code.  Feel free to close this if you can't see why it might not be working.

**Comment by hklages** [comment] 2021-08-19 15:54
It seems to work as designed (by Sonos). Will close the issue.

You may consider to rename the duplicate albums (or add the artist to the album tittle). 

Thanks for the feedback.

**Closed by hklages** 2021-08-19 15:54 UTC
